### ISSUE TITLE
Configuration environment

### ISSUE THREAD

**Issue by osmint** [surban/TensorAlgDiff#1]
I added the tensor library to the TensorAlgDiff project by running the command "dotnet add reference PATH".  

However, it still returned errors like "FourierMotzkin.fs(17,24): error FS0039: The type 'Rat' is not defined."

Do I need to change the file content in "Progrm.fs"? Can you help me how to solve it?

**Comment by surban** [comment]
This was caused by changes in our Tensor library.

I have updated the repository. Please pull and try again. If it still does not work, please let me know.
